//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMemberShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulation
    {
        public int Id { get; set; }
        public string Presentation { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int UsersId { get; set; }
        public int StagesId { get; set; }
        public string etat { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Stages Stages { get; set; }
    }
}
